### PR TITLE
Updated Make a Submission

### PR DESCRIPTION
**Pull request by amandastevens**
Explained how to make a submission if have a Reviewer role but not an Author role.

### CODE REVIEW

**Comment by asmecher** [comment]
This is a work-around for https://github.com/pkp/pkp-lib/issues/4412, correct? I'd suggest that we merge this for `ojs-stable-3_1_2` (for any further 3.1.2 releases -- we're likely to have at least one small one before 3.2 comes out) but leave the `master` branch as is so that #4412 can be fixed instead.

**Comment by amandastevens** [comment]
That sounds good to me!

**Comment by asmecher** [comment]
I think you'll have to close this PR, then open a new one, making sure to target the `stable-3_1_2` branch rather than `master`.

**Comment by amandastevens** [comment]
I made the new PR in the stable 3.1.2 branch and will now close this.

**Pull request closed without merging**
