### PR TITLE
Added Danish translation

### PR DESCRIPTION
**Pull request by neffe**
Hi,
Here's a Danish translation of the OJS 3.0 User Guide. Hope that my edition will be merged into the other guides.
Best regards
Niels Erik Frederiksen

### CODE REVIEW

**Comment by neffe** [comment]
Now I've changed the file names and corrected the links

**Comment by mtub** [comment]
Thanks @neffe. There are a few issues with the inline chapter links: in some places you have copied the links (e.g. `editorial-workflow.md#deltagere`), but you haven't created the anchors (which are HTML anchors, e.g. `<a name="workflow-library"></a>Publisher Library`). I suggest comparing the English and the Danish files with regards to links and anchors (also, I suggest leaving the anchor names in English).

**Comment by neffe** [comment]
Thanks mtub
Is this correct?

```
[Deltagere](editorial-workflow.md#participants)

## <a name="participants"></a>Deltagere
```
The first code line is the inline and the second is the section line

**Comment by mtub** [comment]
It is correct, yes.

**Pull request merged**
